#
# This is generated .travis.yml file, to make actual changes please edit file:
# dev/travis/.travis.yml
#

language: android
dist: trusty
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by project
    - build-tools-26.0.2

    # The SDK version used to compile project
    - android-@ANDROID_SDK_COMPILE@

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-@ANDROID_SDK_COMPILE@"